Repository KSP-RO/RealismOverhaul, pull requests merged in 2020-03, with the labels that each got.

#2198 NewTanks
  GameData/RealismOverhaul/RO_RealFuels.cfg
  GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_ProceduralParts.cfg
Labels: Help Wanted - General

#2192 Add AJ10 Transtar
  GameData/RealismOverhaul/Engine_Configs/AJ10_Transtar_Config.cfg
Labels: Help Wanted - General

#2206 Lunex RL10
  GameData/RealismOverhaul/Engine_Configs/RL10_Config.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/CryoEngines/RO_CryoEngines_Engines.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Engines_USUpper.cfg
Labels: Help Wanted - General

#2194 Update M1 with more accurate data
  GameData/RealismOverhaul/Engine_Configs/M1_Config.cfg
Labels: Help Wanted - General

#2197 Add Speculative, prototype, and modern engines
  GameData/RealismOverhaul/Engine_Configs/AMBR_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/AR1_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/COBRAHigh_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/COBRA_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/DFMMHPE.cfg
  GameData/RealismOverhaul/Engine_Configs/LR129_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/MB35_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/MB45_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/MB60_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RD0162_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RD0164_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RD0169_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RS2100_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RS68_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RS76_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RS83_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RS84_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/SSME_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/STBE1_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/STME_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/TR107_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/XLR132_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/YF-77.cfg
Labels: Help Wanted - General

#2195 Add Ablator to RS68
  GameData/RealismOverhaul/Engine_Configs/RS68_Config.cfg
Labels: Help Wanted - General

#2235 Add 38 cm size options to realchute
  GameData/RealismOverhaul/RO_RecommendedMods/RO_RealChute.cfg
Labels: Help Wanted - Test A Mod

#2252 Stock mk2 bicoupler
  GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Spaceplanes.cfg
Labels: Completed 1 Review Pass

#2255 Restore original ejection force on payload bases
  GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_pFairings.cfg
Labels: Ready to Merge?
