Repository KSP-RO/RealismOverhaul, pull requests merged in 2020-04, with the labels that each got.

#2247 More BDB configs.
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_AtlasV.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_Avionics.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_ProbeExpansion.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_Probes.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB-Solids-Uppers.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Able.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Agena.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Apollo.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Atlas_Classic.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Centaur.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Delta.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Explorer_BabySargent.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Generic.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Juno.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Jupiter.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_LEM.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Mercury.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Probe_Motors.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Redstone.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Saturn_Liquid_new.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Saturn_small_solid_motors.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Sepatrons.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Thor.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Titan_Liquid.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Titan_Solids.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_RealPlume/BDB_Vanguard_Vega.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_SAF.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_Solids.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_agena.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_engines.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_keyhole.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_mercury.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_misc.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_payload_separators.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Bluedog_DB/RO_BDB_tanks.cfg
Labels: Help Wanted - Test A Mod

#2256 Fix issue with KSPWheel when VSR is installed, lower steering response
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-gear-bayMed.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-gear-baySmall.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-gear-fixedMicro.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-wheel-large.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-wheel-medium.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KSPWheelStockPatches/Stock-wheel-small.cfg
Labels: Completed 1 Review Pass

#2253 KIS/KAS compatibility
  GameData/RealismOverhaul/RO_SuggestedMods/KAS-KIS/KAS.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/KAS-KIS/KIS.cfg
Labels: Completed 1 Review Pass

#2258 Add power consupmtion to NSTAR Ion Engine
  GameData/RealismOverhaul/Engine_Configs/NSTAR_Config.cfg
Labels: Help Wanted - Test A Mod

#2268 Configure SRM fuel load
  GameData/RealismOverhaul/Engine_Configs/AJ260FL_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/AJ260SL_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/AJ60A_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_120_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_30A_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_30B_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_30XL_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_4AXL_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_4A_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Castor_4_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/GEM40_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/GEM46_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/GEM63XL_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/GEM63_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RSRMV_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/RSRM_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/SRMU_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/UA1204_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/UA1205_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/UA1206_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/UA1207_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/UA1208_Config.cfg
Labels: Completed 1 Review Pass, Hold For Release

#2264 Improved kOS and RO integration
  GameData/RealismOverhaul/Parts/Avionics/Sounding0-3m.cfg
  GameData/RealismOverhaul/RealismOverhaul_Global_Config.cfg
Labels: Help Wanted - Test A Mod

#2267 Better guesstimates for the Rutherford engines.
  GameData/RealismOverhaul/Engine_Configs/Rutherford_Config.cfg
  GameData/RealismOverhaul/Engine_Configs/Rutherford_Vac_Config.cfg
Labels: Help Wanted - Test A Mod

#2239 Updates to Universal Storage 2 configs
  GameData/RealismOverhaul/RO_SuggestedMods/UniversalStorage/RO_UniversalStorage_2.cfg
Labels: Help Wanted - Test A Mod

#2259 Ion engine and NFP configs rework
  GameData/RealismOverhaul/Engine_Configs/NSTAR_Config.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/NearFutureTechnologies/RO_NearFuture_Propulsion_Engines.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/NearFutureTechnologies/RO_NearFuture_Propulsion_Tanks.cfg
  GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg
Labels: In Progress
